### ISSUE TITLE
Have Gateway add decoded data to existing man/servicedata and not overwrite it

### ISSUE THREAD

**Issue by DigiH** [theengs/gateway#105]
As discussed - have Gateway add decoded data to existing man/servicedata and not overwrite it to have consistent behaviour with OMG. Then leave or remove advertisement and advanced data for publishing depending on **pubadvdata** state.

"mac_type" and "adv_type" might not be in the original Bleak data.

https://github.com/1technophile/OpenMQTTGateway/blob/development/main/ZgatewayBT.ino#L1000

https://docs.openmqttgateway.com/use/ble.html#advanced-publishing-advertisement-and-advanced-data-default-false

And also filtering the newly introduced type tag RMAC, so that no known devices which randomly change their MAC address are actually being published, as default or with related **pubRandomMACs** run parameter

https://github.com/1technophile/OpenMQTTGateway/blob/development/main/ZgatewayBT.ino#L1010

**Comment by koenvervloesem** [comment]
Closing, this has been solved in:
- https://github.com/theengs/decoder/pull/327
- https://github.com/theengs/gateway/pull/127
- https://github.com/theengs/gateway/pull/128
