### ISSUE TITLE
[BT disabled] It runs but I can not see anything published

### ISSUE THREAD

**Issue by matlab22** [theengs/gateway#107]
**Describe the bug**
I can not see anything published on the mqtt server. I do not see any log or status. OS it is hard to describe the error.
I run it from the command line without any success 
`python3 -m TheengsGateway -H "192.168.2.40" -u "user" -p "mypassword" -pt "TheengsGateway"`

, then I tried the service:

```
Mar 13 22:08:50 DietPi systemd[1]: Started Theengs Gateway.
░░ Subject: A start job for unit TheengsGateway.service has finished successfully
░░ Defined-By: systemd
░░ Support: https://www.debian.org/support
░░ 
░░ A start job for unit TheengsGateway.service has finished successfully.
░░ 
░░ The job identifier is 191.
Mar 13 22:08:50 DietPi sudo[9751]: pam_unix(sudo:session): session closed for user root
root@DietPi:/usr/local/bin/theengs_gateway# sudo systemctl restart --now TheengsGateway.service
root@DietPi:/usr/local/bin/theengs_gateway# sudo systemctl restart --now TheengsGateway.service
root@DietPi:/usr/local/bin/theengs_gateway# sudo systemctl stop --now TheengsGateway.service
root@DietPi:/usr/local/bin/theengs_gateway# systemctl status TheengsGateway
● TheengsGateway.service - Theengs Gateway
     Loaded: loaded (/etc/systemd/system/TheengsGateway.service; enabled; vendor preset: enabled)
     Active: inactive (dead) since Mon 2023-03-13 22:18:03 GMT; 4s ago
    Process: 9931 ExecStart=/usr/bin/python3 -m TheengsGateway -H 192.168.2.40 -u user -p mypassword (code=killed, signal=TERM)
   Main PID: 9931 (code=killed, signal=TERM)
        CPU: 552ms

Mar 13 22:12:21 DietPi systemd[1]: Started Theengs Gateway.
Mar 13 22:18:03 DietPi systemd[1]: Stopping Theengs Gateway...
Mar 13 22:18:03 DietPi systemd[1]: TheengsGateway.service: Succeeded.
Mar 13 22:18:03 DietPi systemd[1]: Stopped Theengs Gateway.
root@DietPi:/usr/local/bin/theengs_gateway# 
```

**Environment (please complete the following information):**
* version used (0.8)

**Additional context**
First I installed it using pip and got a lot of compiler errors. Finally I was able to solve them by installing all de dependents. There is a headerfile missing Python.h, so I had to install "sudo apt-get install python3-dev" to resolve it.

**Comment by koenvervloesem** [comment]
Can you run Theengs Gateway with option `-ll DEBUG`? This should show us more information about what is happening.

As for your additional context: can you open a separate issue about that and show us the detailed compiler errors and how you solved this? I see you are using DietPi, your input could help us improve the installation experience for other DietPi users.

**Comment by matlab22** [comment]
Unfortunately I do not know how to recover the compiler errors. Is it possible to get it after a restart?

I run it in debug and it shows not much more:
```
root@DietPi:/usr/local/bin/theengs_gateway# python3 -m TheengsGateway -H "192.168.2.40" -u "usr" -p "pw" -pt "TheengsGateway" -ll DEBUG
INFO:BLEGateway:Starting BLE scan
INFO:BLEGateway:Connected to MQTT Broker!
INFO:BLEGateway:Subscribed to home/+/BTtoMQTT/undecoded
```

**Comment by koenvervloesem** [comment]
Let's just focus on this issue then for now.

MQTT connection seems to work, so the problem is BLE-related. What does `hciconfig` show? What kind of Bluetooth adapter are you using? What hardware are you running DietPi on?

**Comment by matlab22** [comment]
OS:  DietPi v8.15.2
Device model : RPi 4 Model B (aarch64)

I am trying to use the internal Bluetooth module. But it looks like it is not running:

```
root@DietPi:~# hciconfig 
bash: hciconfig: command not found
root@DietPi:~# sudo apt-get install bluez
```

Then I tired to get the status of it:
```
root@DietPi:~# hciconfig
Can't open HCI socket.: Address family not supported by protocol
root@DietPi:~# rfkill list
bash: rfkill: command not found
root@DietPi:~# sudo systemctl status bluetooth
● bluetooth.service - Bluetooth service
     Loaded: loaded (/lib/systemd/system/bluetooth.service; enabled; vendor preset: enabled)
     Active: inactive (dead)
       Docs: man:bluetoothd(8)
```
I tried to restart the module:

```
root@DietPi:~# hciconfig
Can't open HCI socket.: Address family not supported by protocol
root@DietPi:~# systemctl --type=service | grep -i bluetooth
root@DietPi:~# sudo systemctl start bluetooth
root@DietPi:~# sudo systemctl enable bluetooth
Synchronizing state of bluetooth.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable bluetooth
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
        LANGUAGE = (unset),
        LC_ALL = (unset),
        LANG = "en_US.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
        LANGUAGE = (unset),
        LC_ALL = (unset),
        LANG = "en_US.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
root@DietPi:~# sudo systemctl status bluetooth
● bluetooth.service - Bluetooth service
     Loaded: loaded (/lib/systemd/system/bluetooth.service; enabled; vendor preset: enabled)
     Active: inactive (dead)
       Docs: man:bluetoothd(8)

Mar 14 10:29:15 DietPi systemd[1]: Condition check resulted in Bluetooth service being skipped.
Mar 14 10:31:15 DietPi systemd[1]: Condition check resulted in Bluetooth service being skipped.
Mar 14 10:32:32 DietPi systemd[1]: Condition check resulted in Bluetooth service being skipped.
Mar 14 10:33:03 DietPi systemd[1]: Condition check resulted in Bluetooth service being skipped.
Mar 14 10:35:51 DietPi systemd[1]: Condition check resulted in Bluetooth service being skipped.
```

Do I need to enable wifi as well?

**Comment by koenvervloesem** [comment]
I'm not familiar with DietPi, but did you enable Bluetooth in `dietpi-config` advanced options [as suggested here](https://dietpi.com/forum/t/enable-bluetooth/14205/12)? A reboot afterwards may be needed.

Also (but unrelated): you don't need `sudo` when you're already logged in as root.

**Comment by matlab22** [comment]
HALLELUJA
the ones who can read are always a step ahead 😵‍💫 
![image](https://user-images.githubusercontent.com/46869303/224981308-5288db7b-b356-4b9a-b14f-51a262727e31.png)
I tried a lot and probably messed up a few things. I will make a clean install and document the needed steps to get it running

**Comment by matlab22** [comment]
could you add an error message, when no bt device is found?

**Comment by koenvervloesem** [comment]
I'm glad it works now! Yes, we're very interested in the detailed steps to get Theengs Gateway working on DietPi.

We'll try to figure out how we can find whether there's a Bluetooth device found or not. An error message in this case would be very helpful indeed.
