### ISSUE TITLE
Make Bluetooth adapter optional

### ISSUE THREAD

**Issue by kabili207** [theengs/gateway#115]
**Is your feature request related to a problem? Please describe.**
Currently the gateway cannot be used without a BLE adapter. While this isn't an issue when running on a raspberry pi or a PC with sufficient USB ports, this becomes a problem if you try to run it solely as a decoder out in the cloud (ie. as a central decoder for several distant locations)

**Describe the solution you'd like**
I would like to be able to run the gateway without needing a BLE adapter present.

In order to not conflict with issue #109, this feature should only be enabled if command arg or environment variable is set.

**Describe alternatives you've considered**
There's not really an alternative if you want to run it in the cloud.

**Comment by 1technophile** [comment]
Make sense, especially because a user made it run with another gateway from Ruuvi, also as a MQTTtoMQTT decoder

**Comment by koenvervloesem** [comment]
I implemented this in https://github.com/theengs/gateway/pull/196.

Running `TheengsGateway --ble 0` disables BLE, so you can run it purely for decoding MQTT messages.
