### ISSUE TITLE
Discover Bluetooth Smartphone 

### ISSUE THREAD

**Issue by davidwaze** [theengs/gateway#119]
Hello

Im currently using the app without issues (thanks for the app), all my devices are discovered except my Android smartphones.

Is there a way to be visible from the app ?

If il running sudo hcitool scan (Sena UD100 bluetooth USB key, bluez app installed) my Huawei P30 pro is well detected (static Bluetooth Mac address)

![abc3f27d34b9bce98cc2c8cb0ef01b9aac873dd7](https://user-images.githubusercontent.com/26407047/229342189-acf7b4bc-bc18-4aa4-8e25-f56040e72cf2.png)

I'd imagine this could be the case also into theengs app.

I was looking to discovery filter option with per default :  IBEACON, GEAN , MS-CDP. Is there another filter or make accept all Bluetooth devices? Am I going to the wrong way or isn't it possible?

Thanks for your help.

**Comment by koenvervloesem** [comment]
`hcitool scan` looks for Classic Bluetooth (BR/EDR) devices that are in discoverable mode, while `hcitool lescan` looks for Bluetooth Low Energy (BLE) devices that are advertising. Theengs Gateway only supports Bluetooth Low Energy. So your phones are probably not sending BLE advertisements but using Classic Bluetooth.

**Comment by davidwaze** [comment]
Thanks for your quick answer.

You're right with 'hcitool lescan' phone is not discovered anymore. :-(

What is the limitation of Theengs gateway to bypass 'classic' Bluetooth if the hardware (Bluetooth key) have the capability ?

Couldn't we think to have a command option to have this ?

I've migrated all my home automation through mqtt for my zwave and zigbee devices but still blocked just due tu my Bluetooth smartphone detection problem.

Thanks

**Comment by koenvervloesem** [comment]
Theengs Gateway is using the [Bleak](https://bleak.readthedocs.io) library for cross-platform support, and this supports BLE on Windows, macOS and Linux. If we find a Python library supporting Classic Bluetooth on those three operating systems, we could add it. But it would probably not be trivial to make this work together with BLE simultaneously.

Of course if you're using MQTT you can always add another project for presence detection of your Classic Bluetooth devices. [Room Assistant](https://www.room-assistant.io/integrations/bluetooth-classic.html#bluetooth-classic) seems to tick all the boxes for you.

**Comment by DigiH** [comment]
@davidwaze 

Just FYI - to have your static Bluetooth MAC address Huawei P30 Pro, if you still have it, discovered with BLE advertisements, you could install [Beacon Scope](https://play.google.com/store/apps/details?id=com.davidgyoungtech.beaconscanner) to have it transmit iBeacon BLE broadcasts. 

And depending on which controller you are using, if entering the iBeacon UUID
`54686565-6E67-732D-6942-6561636F6E31`
the phone will automatically be discovered as a device_tracker.
