### ISSUE TITLE
Apple device filter not working?

### ISSUE THREAD

**Issue by yndtrud** [theengs/gateway#126]
1) I installed a filter (discovery_filter) on devices from apple, but they are still published in MQTT.
Am I doing something wrong or do I misunderstand the logic of the filter?
Is my config file free of errors?

2)  Is it possible to filter some devices by MAC  address (which use a static MAC) or brand?

`
{
    "adapter": "",
    "ble_scan_time": 5,
    "ble_time_between_scans": 5,
    "discovery": 1,
    "discovery_device_name": "bledev",
    "discovery_filter": [
        "IBEACON",
        "GAEN",
        "MS-CDP",
        "APPLE_CONT",
        "APPLE_CONTAT",
        "BPARASITE"
    ],
    "discovery_topic": "ble2mqtt/discovery",
    "hass_discovery": 0,
    "host": "somehost",
    "log_level": "DEBUG",
    "lwt_topic": "ble2mqtt/status",
    "pass": "somepwd",
    "port": 1883,
    "presence": 1,
    "presence_topic": "ble2mqtt/presence",
    "publish_all": 1,
    "publish_topic": "ble2mqtt/device",
    "scanning_mode": "active",
    "subscribe_topic": "ble2mqtt/device/set",
    "time_format": 0,
    "time_sync": [],
    "user": "someusr"
}
`
![2023-04-13_115433](https://user-images.githubusercontent.com/67788055/231709071-fdd0156c-f944-4a62-ac40-02d3823581f2.png)

**Comment by yndtrud** [comment]
Oh, my god! Apple + Samsung

![2023-04-13_222023](https://user-images.githubusercontent.com/67788055/231954502-d63be057-e5a5-4408-8a4e-1756c307fdf1.png)
![2023-04-13_222038](https://user-images.githubusercontent.com/67788055/231954510-9b6fe24d-a32f-40b4-82bf-35383cb87132.png)
![2023-04-13_222046](https://user-images.githubusercontent.com/67788055/231954521-8f2f768d-b921-4c21-a8bc-31f4febc20ee.png)

**Comment by 1technophile** [comment]
This filter avoids the listed model_id being discovered, it does not prevent them from being published. The goal is mainly to avoid the discovered retained by the broker. The others are not.
We are going to enrich the filter to remove from discovery and real-time the devices with random macs

**Comment by yndtrud** [comment]
How do you say )
