### ISSUE TITLE
set path to theengsgw.conf

### ISSUE THREAD

**Issue by matlab22** [theengs/gateway#132]
**Is your feature request related to a problem? Please describe.**
I am using a special version of DietPi called Loxberry. On every update it deletes all unrelated stuff in the user folder

**Describe the solution you'd like**
could you please provide an option to set the path to the theengsgw.conf file?

**Comment by koenvervloesem** [comment]
This has been implemented in https://github.com/theengs/gateway/pull/143 and will be available in the next version of Theengs Gateway.
