### ISSUE TITLE
Docker version is not updated

### ISSUE THREAD

**Issue by Bolukan** [theengs/gateway#152]
**Describe the bug**
The latest docker version (https://hub.docker.com/r/theengs/gateway) is not current.
It is from 4 months ago and does not include the lateste release (https://github.com/theengs/gateway/releases/tag/v1.1.0)

**To Reproduce**
Renew the container to be sure
bash into the image
Look into /opt/venv/lib/python3.9/site-packages/ and run the diagnose.

**Expected behavior**
The docker container is updated within 24 hours of a new release.

**Environment**
| Name               | Value  |
|--------------------|--------|
| Theengs Gateway    | 0.9.0  |
| Theengs Decoder    | 1.3.7  |
| Bleak              | 0.20.1 |
| Bluetooth Clocks   | 0.1.2  |
| Bluetooth Numbers  | 1.1.0  |
| Paho MQTT          | 1.6.1  |
| Bluetooth Adapters | 0.15.3 |

## Python

| Name           | Value                 |
|----------------|-----------------------|
| Version        | 3.9.16                |
| Implementation | CPython               |
| Compiler       | GCC 10.2.1 20210110   |
| Executable     | /usr/local/bin/python |

**Comment by konfilios** [comment]
Same issue here, and the problem is that the old version doesn't work with my hardware/setup

**Comment by DigiH** [comment]
~~@maretodoric - any chance of getting your great Docker version up to date with the Gateway releases?~~

Apologies @maretodoric, I didn't realise that we had actually taken over the Docker side from you :) we'll get it updated.

Thanks

**Comment by DigiH** [comment]
Version 1.1.0.2

https://github.com/theengs/gateway-docker

**Comment by maretodoric** [comment]
That's ok. I'm happy to help if there is anything needed :)
