### ISSUE TITLE
Question regarding sensor data from Xiaomi LYWSD03MMC, through MQTT / TheengsGateway

### ISSUE THREAD

**Issue by skxctech** [theengs/gateway#167]
Hello, I’m trying to set up some LYWSD03MMC sensors, my setup being:
* Home Assistant running on a server / hyper-v, Mosquitto Addon
* TheengsGateway running on a RPI Zero W
  
I’ve got Mosquitto set up on the HA machine and the RPI/TheengsGateway sending data. Data received in the broker currently looks like this:

```
{
  "servicedatauuid": "fe95",
  "servicedata": "30585b0506307a6a38c1a408",
  "name": "LYWSD03MMC",
  "id": "A4:C1:38:6A:7A:30",
  "rssi": -42,
}
```
I understood I need a bind key for the Xiaomi sensor, grabbed it using - [Telink Flasher](https://atc1441.github.io/TelinkFlasher.html), but I have no ideea where to add it. Any clue?

If I had bluetooth in hyper-v, using the TheengsGateway addon home assistant discovery would kick in and ask through Xiaomi BLE integration for the key - but when running the gateweay on the RPI I'm not sure how to add it.

**Comment by koenvervloesem** [comment]
What firmware is running on the LYWSD03MMC? What Theengs Gateway version is this? Support for decrypting (some) encrypted advertisements with bindkeys is a recent addition and for now only available in the development version of Theengs Gateway.

**Comment by skxctech** [comment]
Firmware is the one with LYWSD03MMC_ATC - I believe that's the firmware indicator for the sensor?

Installed through pip:

TheengsDecoder     1.5.7
TheengsGateway     1.1.0

I'll try and use the development version

**Comment by koenvervloesem** [comment]
You also need the development version of Theengs Decoder. The process to add the bindkeys is explained in the development version of the docs: https://github.com/theengs/gateway/blob/development/docs/use/use.md#reading-encrypted-advertisements. Let us know if this works for you.

**Comment by skxctech** [comment]
Found some custom firmware - [atc1441/ATC_MiThermometer](https://github.com/atc1441/ATC_MiThermometer). Reporting fine now, no need for bind key!

Tried setting up the dev version, gateway was easy but I don't have an environment to build the decoder.
