### ISSUE TITLE
Discovery with non-numeric sensor values broken

### ISSUE THREAD

**Issue by kabili207** [theengs/gateway#182]
**Describe the bug**
According to the Home Assistant documentation for sensors, non-null values for the `state_class` property in the discovery config mean that the sensor is assumed to report numeric values.

> Type of state. If not None, the sensor is assumed to be numerical and will be displayed as a line-chart in the frontend instead of as discrete values.

Currently, the `state_class` option is hard-coded to the value "measurement" (see [here](https://github.com/theengs/gateway/blob/development/TheengsGateway/discovery.py#L176)). This causes issues with some sensors that report string values, such as the LYWSD02, which reports it's mac address as a sensor value.

**Expected behavior**
The `state_class` should be either omitted or set to `None` if a sensor value will be non-numeric

**Screenshots**
Example state
```json
{
  "name": "LYWSD02",
  "id": "E7:2E:00:21:20:AE",
  "rssi": -84,
  "brand": "Xiaomi/Mijia",
  "model": "e-ink Clock",
  "model_id": "LYWSD02",
  "type": "THB",
  "batt": 24,
  "mac": "E7:2E:00:21:20:AE"
}
```

Config for the "mac" sensor
```json
{
  "stat_t": "+/+/BTtoMQTT/E72E002120AE",
  "name": "LYWSD02-mac",
  "uniq_id": "E72E002120AE-mac",
  "val_tpl": "{{ value_json.mac }}",
  "state_class": "measurement",
  "device": { /* snip */ }
}
```

And an unhappy OpenHAB complaining about the incoming state due to the improper config
```
22:15:37.870 [WARN ] [hab.binding.mqtt.generic.ChannelState] - Incoming payload 'E7:2E:00:21:20:AE' on 'home/TheengsGateway/BTtoMQTT/E72E002120AE' not supported by type 'NumberValue'
22:15:41.930 [WARN ] [hab.binding.mqtt.generic.ChannelState] - Incoming payload 'E7:2E:00:21:20:AE' on 'home/TheengsGateway/BTtoMQTT/E72E002120AE' not supported by type 'NumberValue'
```

**Environment**
# Theengs Gateway Diagnostics
## Package Versions
| Name               | Value                      |
|--------------------|----------------------------|
| Theengs Gateway    | 1.1.0.post1.dev27+g2b08151 |
| Theengs Decoder    | 1.6.3                      |
| Bleak              | 0.21.1                     |
| Bluetooth Clocks   | 0.2.0                      |
| Bluetooth Numbers  | 1.1.1                      |
| Paho MQTT          | 1.6.1                      |
| Bluetooth Adapters | 0.16.1                     |
## Python
| Name           | Value                 |
|----------------|-----------------------|
| Version        | 3.9.18                |
| Implementation | CPython               |
| Compiler       | GCC 12.2.1 20220924   |
| Executable     | /opt/venv/bin/python3 |
## Operating System
| Name         | Value                                 |
|--------------|---------------------------------------|
| System       | Linux                                 |
| Release      | 5.10.103-v7+                          |
| Version      | #1529 SMP Tue Mar 8 12:21:37 GMT 2022 |
| Machine type | armv7l                                |
## Configuration
File: /root/theengsgw.conf
```
{
    "adapter": "hci0",
    "bindkeys": {},
    "ble_scan_time": 60,
    "ble_time_between_scans": 60,
    "discovery": true,
    "discovery_device_name": "TheengsGateway",
    "discovery_filter": "[IBEACON,GAEN,MS-CDP,TPMS,APPLE_CONT,APPLE_CONTAT,TILE]",
    "discovery_topic": "homeassistant/sensor",
    "enable_tls": 0,
    "enable_websocket": 0,
    "hass_discovery": false,
    "host": "mqtt.zyrenth.com",
    "identities": {},
    "log_level": "DEBUG",
    "lwt_topic": "home/TheengsGateway/LWT",
    "pass": "***",
    "port": 1883,
    "presence": false,
    "presence_topic": "home/presence/TheengsGateway",
    "publish_advdata": false,
    "publish_all": false,
    "publish_topic": "home/TheengsGateway/BTtoMQTT",
    "scanning_mode": "active",
    "subscribe_topic": "home/+/BTtoMQTT/undecoded",
    "time_format": "0",
    "time_sync": [
        "INVALID ADDRESS",
        "INVALID ADDRESS"
    ],
    "user": "***"
}
```
## Bluetooth adapters
Default adapter: hci0
### hci0
| Name         | Value                   |
|--------------|-------------------------|
| address      | B8:27:EB:XX:XX:XX       |
| sw_version   | naomi                   |
| hw_version   | usb:v1D6Bp0246d0532     |
| passive_scan |                       0 |
| manufacturer | Raspberry Pi Foundation |

**Additional context**
Add any other relevant context about the problem here.

**Comment by 1technophile** [comment]
Hello,

You are right, currently Theengs gateway only consider the type sensor for discovery where it should differentiate the binary sensors, text sensors ...
We would have to change the current default configuration of the discovery topic to not finish by "sensor" and identify the different categories with the informations given by the decoder.
Also the 'mac' should be filtered in my point of view.

**Comment by 1technophile** [comment]
Working on it

**Comment by 1technophile** [comment]
Done, feel free to reopen if any comments
