### ISSUE TITLE
Installing Theengs Gateway on Raspberry Pi OS (Bookworm)

### ISSUE THREAD

**Issue by tech9492** [theengs/gateway#227]
Hi,

I am trying to install Theengs Gateway on a Raspberry Pi 3A+ loaded with Bookworm (64bit). I managed to install `pip` with `sudo apt install python3-pip`. 

However, executing `pip3 install TheengsGateway`, throws the following message `error: externally-managed-environment`. After researching, found out it is due to a new security feature in Debian 12. It is to prevent conflict between OS installed python packages and user installed python packages. Hence, it is advised to install non-OS packages in a python virtual environment. 

Has anyone successfully installed TheengsGateway in a virtual environment and run it system-wide? Could you please elaborate the steps.

Thank you.

**Comment by DigiH** [comment]
Hi @tech9492 

Have you tried something like

`python3 -m venv .venv`

then

`source .venv/bin/activate`

**Comment by koenvervloesem** [comment]
You should be able to run Theengs Gateway [as a systemd service](https://github.com/theengs/gateway/discussions/5#discussioncomment-8172229), but with `ExecStart` referring to your `venv/bin/python3 -m TheengsGateway`, and the `Environment` line removed.

Give it a try? Then we can add this to the documentation.

**Comment by tech9492** [comment]
@koenvervloesem, alright I will give this a try. 

Should `--system-site-packages` be true when creating the virtual environment?

Thank you.

**Comment by koenvervloesem** [comment]
That shouldn't be necessary, I think. But, as with many things in life, just try :-)

**Comment by tech9492** [comment]
Just to update, I successfully installed TheengsGateway within a virtual environment. 

However, when I execute the following `python -m TheengsGateway -H “localhost” -u “USERNAME” -p “PASSWORD”` within the environment it throws the following;
```
Traceback (most recent call last):
  File "<frozen runpy>", line 189, in _run_module_as_main
  File "<frozen runpy>", line 148, in _get_module_details
  File "<frozen runpy>", line 112, in _get_module_details
  File "/home/logger/theengs/lib/python3.11/site-packages/TheengsGateway/__init__.py", line 24, in <module>
    from .ble_gateway import run
  File "/home/logger/theengs/lib/python3.11/site-packages/TheengsGateway/ble_gateway.py", line 58, in <module>
    from bleak.backends.bluezdbus.advertisement_monitor import OrPattern
  File "/home/logger/theengs/lib/python3.11/site-packages/bleak/backends/bluezdbus/advertisement_monitor.py", line 12, in <module>
    from dbus_fast.service import ServiceInterface, dbus_property, method, PropertyAccess
  File "/home/logger/theengs/lib/python3.11/site-packages/dbus_fast/__init__.py", line 1, in <module>
    from . import introspection, message_bus, proxy_object, service
  File "/home/logger/theengs/lib/python3.11/site-packages/dbus_fast/introspection.py", line 5, in <module>
    from .errors import InvalidIntrospectionError
  File "/home/logger/theengs/lib/python3.11/site-packages/dbus_fast/errors.py", line 57, in <module>
    from .message import Message
  File "src/dbus_fast/message.py", line 1, in init dbus_fast.message
ValueError: dbus_fast.signature.Variant size changed, may indicate binary incompatibility. Expected 48 from C header, got 40 from PyObject
```

Below is a list of steps I followed, maybe I missed out on something since this is my first attempt with python virtual environment.

1. `python --version` returns Python 3.11.2 already installed
2. `sudo apt install python3-pip`
3. `python3 -m venv --system-site-packages theengs`
4. `source theengs/bin/activate`
5. `pip3 install TheengsGateway`

Thank you.

**Comment by koenvervloesem** [comment]
You probably have multiple versions of dbus-fast installed. See here for an explanation and a solution: https://github.com/home-assistant/core/issues/102605

Did you install dbus-fast first as a system package? Maybe the venv picks it up because you created it with the `--system-site-packages` option. Didn't it work without this option?

I just replicated your steps on a clean bookworm VM (adding `sudo apt install python3.11-venv` and not using the `--system-site-packages` option when creating the virtual environment) and I don't get this error. So this probably is some leftover from a previous installation.

**Comment by tech9492** [comment]
No, I did not install dbus-fast.

I am actually doing this on a fresh raspberry pi OS. I did try it a few days ago without `--system-site-packages`, it threw some errors when executing `python -m TheengsGateway -H “localhost” -u “USERNAME” -p “PASSWORD”` .

I will erase the SD card and get a fresh install and try it without `--system-site-packages`.

**Comment by tech9492** [comment]
Executed `pip3 install TheengsGateway` on a clean OS within a virtual environment without `--system-site-packages`. Below is part of the installation log, since it is still building. 

I am guessing `dbus-fast` is installed as part of `bluetooth-adapters`. [piwheels](https://www.piwheels.org/project/bluetooth-adapters/) marked `bluetooth-adapters 0.15.3` as build pending for Python 3.11. And for [dbus-fast](https://www.piwheels.org/project/dbus-fast/) version 1.83.0 build succeeded for Python 3.11.
 
 
 
>  You probably have multiple versions of dbus-fast installed. See here for an explanation and a solution: https://github.com/home-assistant/core/issues/102605

To ease the troubleshooting process, should I downgrade or upgrade `dbus-fast`?
 
 
 

```
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting TheengsGateway
  Downloading https://www.piwheels.org/simple/theengsgateway/TheengsGateway-1.3.0-py3-none-any.whl (32 kB)
Collecting bleak>=0.19.0
  Downloading https://www.piwheels.org/simple/bleak/bleak-0.21.1-py3-none-any.whl (137 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 137.8/137.8 kB 500.4 kB/s eta 0:00:00
Collecting bluetooth-clocks<1.0
  Downloading https://www.piwheels.org/simple/bluetooth-clocks/bluetooth_clocks-0.2.0-py3-none-any.whl (20 kB)
Collecting bluetooth-numbers<2.0,>=1.0
  Downloading https://www.piwheels.org/simple/bluetooth-numbers/bluetooth_numbers-1.1.1-py3-none-any.whl (474 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 474.1/474.1 kB 643.9 kB/s eta 0:00:00
Collecting importlib-metadata
  Downloading importlib_metadata-7.0.1-py3-none-any.whl (23 kB)
Collecting paho-mqtt>=1.6.1
  Downloading https://www.piwheels.org/simple/paho-mqtt/paho_mqtt-1.6.1-py3-none-any.whl (75 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 75.6/75.6 kB 298.6 kB/s eta 0:00:00
Collecting pycryptodomex>=3.18.0
  Downloading pycryptodomex-3.20.0-cp35-abi3-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (2.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 609.8 kB/s eta 0:00:00
Collecting TheengsDecoder>=1.6.4
  Downloading TheengsDecoder-1.6.8.tar.gz (296 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 296.4/296.4 kB 368.1 kB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Collecting bluetooth-adapters>=0.15.3
  Downloading https://www.piwheels.org/simple/bluetooth-adapters/bluetooth_adapters-0.17.0-py3-none-any.whl (19 kB)
Collecting dbus-fast<3,>=1.83.0
  Downloading dbus_fast-2.21.1.tar.gz (69 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 69.4/69.4 kB 2.8 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting typing-extensions>=4.7.0
  Using cached https://www.piwheels.org/simple/typing-extensions/typing_extensions-4.9.0-py3-none-any.whl (32 kB)
Collecting aiohttp>=3.8.1
  Downloading aiohttp-3.9.1-cp311-cp311-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (1.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 3.8 MB/s eta 0:00:00
Collecting mac-vendor-lookup>=0.1.12
  Downloading mac_vendor_lookup-0.1.12-py3-none-any.whl (350 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 350.3/350.3 kB 3.8 MB/s eta 0:00:00
Collecting usb-devices>=0.4.5
  Downloading https://www.piwheels.org/simple/usb-devices/usb_devices-0.4.5-py3-none-any.whl (5.3 kB)
Collecting zipp>=0.5
  Downloading https://www.piwheels.org/simple/zipp/zipp-3.17.0-py3-none-any.whl (7.4 kB)
Collecting attrs>=17.3.0
  Downloading https://www.piwheels.org/simple/attrs/attrs-23.2.0-py3-none-any.whl (60 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.8/60.8 kB 8.7 kB/s eta 0:00:00
Collecting multidict<7.0,>=4.5
  Downloading multidict-6.0.4-cp311-cp311-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (120 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 120.1/120.1 kB 2.2 MB/s eta 0:00:00
Collecting yarl<2.0,>=1.0
  Downloading yarl-1.9.4-cp311-cp311-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (324 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 324.2/324.2 kB 2.3 MB/s eta 0:00:00
Collecting frozenlist>=1.1.1
  Downloading frozenlist-1.4.1-cp311-cp311-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (273 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 273.3/273.3 kB 306.8 kB/s eta 0:00:00
Collecting aiosignal>=1.1.2
  Downloading https://www.piwheels.org/simple/aiosignal/aiosignal-1.3.1-py3-none-any.whl (7.6 kB)
Collecting aiofiles
  Downloading https://www.piwheels.org/simple/aiofiles/aiofiles-23.2.1-py3-none-any.whl (15 kB)
Collecting idna>=2.0
  Downloading https://www.piwheels.org/simple/idna/idna-3.6-py3-none-any.whl (61 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.6/61.6 kB 34.7 kB/s eta 0:00:00
Building wheels for collected packages: TheengsDecoder, dbus-fast
  Building wheel for TheengsDecoder (pyproject.toml) ... done
  Created wheel for TheengsDecoder: filename=TheengsDecoder-1.6.8-cp311-cp311-linux_aarch64.whl size=61447 sha256=52f357071e2eca21eff2efc6ac8d5fcd26b016ad267383176daf2e620aec4ac8
  Stored in directory: /home/logger/.cache/pip/wheels/ca/22/ed/7686f99ee98c9a464d9492ac37c607acab04f38d6bed5cba84
  Building wheel for dbus-fast (pyproject.toml) ... |
```

**Comment by koenvervloesem** [comment]
Just replicated these steps on a Raspberry Pi OS bookworm installation (32-bit, on Raspberry Pi 3B), and installing and running Theengs Gateway works.

Did you succeed in building dbus-fast?

**Comment by tech9492** [comment]
Hi @koenvervloesem 

> Did you succeed in building dbus-fast?

No, I have not been able to build dbus-fast. At times the installation process completes successfully, and sometimes it seems to halt while building dbus-fast.

I was not able to complete the installation last night, it was building the dbus-fast for nearly 4 hours. Today, I started on a fresh OS and its been nearly 2 hours building the dbus-fast(green LED is on). Do you think 64bit might be the issue?

I would be grateful if you could try replicate it on 64bit(Lite).

Thank you.

**Comment by koenvervloesem** [comment]
Then I think it's a 64-bit issue indeed. I don't have a 64-bit Raspberry Pi OS bookworm at hand here, but I'll try to find a spare SD card and Pi to check this tomorrow.

**Comment by koenvervloesem** [comment]
Ok, I just did a clean install of 64-bit Raspberry Pi OS bookworm Lite on a Raspberry Pi OS 4. Then these steps:

```shell
$ sudo apt update
$ sudo apt install python3-pip python3-venv
$ python3 -m venv theengs
$ source theengs/bin/activate
(theengs) $ pip install TheengsGateway
```

Although building `dbus-fast` takes a while (estimated around 5 minutes, but the Raspberry Pi 4 has of course much more processing power than your Raspberry Pi 3A+), installation succeeds, and I can run Theengs Gateway successfully.

Did you encounter a build that really failed, or does it just keep building endlessly?

**Comment by tech9492** [comment]
> Just replicated these steps on a Raspberry Pi OS bookworm installation (32-bit, on Raspberry Pi 3B), and installing and running Theengs Gateway works.

I confirm, Theengs Gateway functions properly on Raspberry Pi OS Bookworm 32bit (Lite). Installation took a couple of minutes compared to hours on 64bit. 

> Did you encounter a build that really failed, or does it just keep building endlessly?

No, I have not encountered any build that failed. For the couple of times I tried, it keeps building endlessly - especially `dbus-fast`.
Twice or thrice I had successful installation but executing `python -m TheengsGateway -H “localhost” -u “USERNAME” -p “PASSWORD”` would throw the `dbus-fast` error.

I will stick to the 32bit. I just read a few comparison of 32bit vs 64bit, the main advantage of 64bit is access to more than 4gb ram. The Raspberry Pi 3A+ has 512mb ram, hence no point of running 64bit. Probably that is the reason for the installation process to take hours or halt.

Thank you very much for your support and precious time :)
