### ISSUE TITLE
Support for Govee H5105 / E-Ink

### ISSUE THREAD

**Issue by markusmainz** [theengs/gateway#247]
Hello my H5105 devices are not recognized corret in theengs Gateway on Raspberry PI 3

**Comment by DigiH** [comment]
Hi @markusmainz 

There is no decoder so far for the Govee H5105, so this is expected.

Could you start Theengs Gateway with the option **PUBLISH_ADVDATA** set to 1, 

> -padv PUBLISH_ADVDATA, --publish_advdata PUBLISH_ADVDATA
>                         Publish advertising and advanced data (1) or not (0)
>                         (default: 0)

and give some sample MQTT messages with the **undecoded manufacturerdata** when monitoring with [MQTT Explorer](https://github.com/thomasnordquist/MQTT-Explorer/releases/tag/v0.3.5), along with the temperature, humidity and battery level at the time of the readings? We can then see if and how we can add a decoder for it.

**Comment by DigiH** [comment]
Hi @markusmainz 

Any update on a raw undecoded manufacturerdata sample message from your Govee H5105, so that we can create a decoder for it?

Most likely it will have a name like "GVH5105" or similar included in the message.

**Comment by markusmainz** [comment]
I see something like this

about
23.6 °C 
44.8 %r.F.


`21.03.2024 20:36:00 
{"manufacturerdata": "0100010103787664", "name": "GVH5105_5D6F", "id": "D0:30:38:35:5D:6F", "rssi": -68, "mfr": "Nokia Mobile Phones"}
21.03.2024 20:35:50(-10.03 seconds) 
{"manufacturerdata": "0100010103787664", "name": "GVH5105_5D6F", "id": "D0:30:38:35:5D:6F", "rssi": -69, "mfr": "Nokia Mobile Phones"}
21.03.2024 20:35:42(-7.98 seconds) 
{"name": "GVH5105_5D6F", "id": "D0:30:38:35:5D:6F", "rssi": -64, "brand": "GENERIC", "model": "iBeacon", "model_id": "IBEACON", "type": "BCON", "mfid": "4c00", "uuid": "494e54454c4c495f524f434b535f4857", "major": 20597, "minor": -3329, "volt": 1.2}
21.03.2024 20:35:40(-2.01 seconds) 
{"manufacturerdata": "0100010103787664", "name": "GVH5105_5D6F", "id": "D0:30:38:35:5D:6F", "rssi": -69, "mfr": "Nokia Mobile Phones"}
21.03.2024 20:35:28(-11.98 seconds) 
{"manufacturerdata": "0100010103787664", "name": "GVH5105_5D6F", "id": "D0:30:38:35:5D:6F", "rssi": -68, "mfr": "Nokia Mobile Phones"}
21.03.2024 20:35:18(-10.01 seconds) 
{"manufacturerdata": "0100010103787664", "name": "GVH5105_5D6F", "id": "D0:30:38:35:5D:6F", "rssi": -63, "mfr": "Nokia Mobile Phones"}
21.03.2024 20:35:14(-3.81 seconds) 
{"manufacturerdata": "0100010103787664", "name": "GVH5105_5D6F", "id": "D0:30:38:35:5D:6F", "rssi": -94, "mfr": "Nokia Mobile Phones"}
21.03.2024 20:35:12(-2.24 seconds) 
{"name": "GVH5105_5D6F", "id": "D0:30:38:35:5D:6F", "rssi": -69, "brand": "GENERIC", "model": "iBeacon", "model_id": "IBEACON", "type": "BCON", "mfid": "4c00", "uuid": "494e54454c4c495f524f434b535f4857", "major": 20597, "minor": -3329, "volt": 1.2}
21.03.2024 20:35:08(-3.9 seconds) 
{"manufacturerdata": "0100010103787664", "name": "GVH5105_5D6F", "id": "D0:30:38:35:5D:6F", "rssi": -64, "mfr": "Nokia Mobile Phones"}
21.03.2024 20:34:58(-10.04 seconds) 
{"manufacturerdata": "0100010103787664", "name": "GVH5105_5D6F", "id": "D0:30:38:35:5D:6F", "rssi": -64, "mfr": "Nokia Mobile Phones"}
21.03.2024 20:34:48(-10.07 seconds) 
{"manufacturerdata": "0100010103787664", "name": "GVH5105_5D6F", "id": "D0:30:38:35:5D:6F", "rssi": -65, "mfr": "Nokia Mobile Phones"}
21.03.2024 20:34:40(-8.02 seconds) 
{"name": "GVH5105_5D6F", "id": "D0:30:38:35:5D:6F", "rssi": -65, "brand": "GENERIC", "model": "iBeacon", "model_id": "IBEACON", "type": "BCON", "mfid": "4c00", "uuid": "494e54454c4c495f524f434b535f4857", "major": 20597, "minor": -3329, "volt": 1.2}
21.03.2024 20:34:38(-1.87 seconds) 
{"manufacturerdata": "0100010103787664", "name": "GVH5105_5D6F", "id": "D0:30:38:35:5D:6F", "rssi": -68, "mfr": "Nokia Mobile Phones"}
21.03.2024 20:34:30(-8.12 seconds) 
{"manufacturerdata": "0100010103787664", "name": "GVH5105_5D6F", "id": "D0:30:38:35:5D:6F", "rssi": -69, "mfr": "Nokia Mobile Phones"}
21.03.2024 20:34:20(-10.01 seconds) 
{"manufacturerdata": "0100010103787664", "name": "GVH5105_5D6F", "id": "D0:30:38:35:5D:6F", "rssi": -64, "mfr": "Nokia Mobile Phones"}
21.03.2024 20:34:08(-11.73 seconds) 
{"manufacturerdata": "0100010103787664", "name": "GVH5105_5D6F", "id": "D0:30:38:35:5D:6F", "rssi": -64, "mfr": "Nokia Mobile Phones"}
21.03.2024 20:33:58(-10.24 seconds) 
{"manufacturerdata": "0100010103787664", "name": "GVH5105_5D6F", "id": "D0:30:38:35:5D:6F", "rssi": -69, "mfr": "Nokia Mobile Phones"}
21.03.2024 20:33:48(-10.03 seconds) 
{"name": "GVH5105_5D6F", "id": "D0:30:38:35:5D:6F", "rssi": -64, "brand": "GENERIC", "model": "iBeacon", "model_id": "IBEACON", "type": "BCON", "mfid": "4c00", "uuid": "494e54454c4c495f524f434b535f4857", "major": 20597, "minor": -3329, "volt": 1.2}
21.03.2024 20:33:46(-1.97 seconds) 
{"manufacturerdata": "0100010103787664", "name": "GVH5105_5D6F", "id": "D0:30:38:35:5D:6F", "rssi": -68, "mfr": "Nokia Mobile Phones"}
21.03.2024 20:33:40(-6 seconds) 
{"name": "GVH5105_5D6F", "id": "D0:30:38:35:5D:6F", "rssi": -64, "brand": "GENERIC", "model": "iBeacon", "model_id": "IBEACON", "type": "BCON", "mfid": "4c00", "uuid": "494e54454c4c495f524f434b535f4857", "major": 20597, "minor": -3329, "volt": 1.2}
21.03.2024 20:33:36(-3.98 seconds) 
{"manufacturerdata": "0100010103787664", "name": "GVH5105_5D6F", "id": "D0:30:38:35:5D:6F", "rssi": -62, "mfr": "Nokia Mobile Phones"}
21.03.2024 20:33:26(-9.99 seconds) 
{"manufacturerdata": "0100010103787664", "name": "GVH5105_5D6F", "id": "D0:30:38:35:5D:6F", "rssi": -65, "mfr": "Nokia Mobile Phones"}
21.03.2024 20:33:22(-3.95 seconds) 
{"manufacturerdata": "0100010103787664", "name": "GVH5105_5D6F", "id": "D0:30:38:35:5D:6F", "rssi": -94, "mfr": "Nokia Mobile Phones"}
21.03.2024 20:33:18(-4.12 seconds) 
{"name": "GVH5105_5D6F", "id": "D0:30:38:35:5D:6F", "rssi": -68, "brand": "GENERIC", "model": "iBeacon", "model_id": "IBEACON", "type": "BCON", "mfid": "4c00", "uuid": "494e54454c4c495f524f434b535f4857", "major": 20597, "minor": -3329, "volt": 1.2}
21.03.2024 20:33:16(-1.97 seconds) 
{"manufacturerdata": "0100010103787664", "name": "GVH5105_5D6F", "id": "D0:30:3`



`{
  "manufacturerdata": "0100010103787664",
  "name": "GVH5105_5D6F",
  "id": "D0:30:38:35:5D:6F",
  "rssi": -63,
  "mfr": "Nokia Mobile Phones"
  "rssi": -69,
  "brand": "GENERIC",
  "model": "iBeacon",
  "model_id": "IBEACON",
  "type": "BCON",
  "mfid": "4c00",
  "uuid": "494e54454c4c495f524f434b535f4857",
  "major": 20597,
  "minor": -3329,
  "volt": 1.2
}`

**Comment by DigiH** [comment]
Hi @markusmainz 

Thanks for the information, but

> about
> 23.6 °C
> 44.8 %r.F.

Could it have been 2**2**.6ºC?

**Comment by markusmainz** [comment]
Ahh you are right i have two of this devices and i read the one in the living room :-)

**Comment by markusmainz** [comment]
i have two theengs gateways running and i collect the data without PUBLISH_ADVDATA i think because only on one gateway i started with this option

**Comment by DigiH** [comment]
How are you running Theengs Gateway, did you do a pip install, or are you running it as a Home Assistant plug-in?

**Comment by markusmainz** [comment]
im running it on rpi as pip install and send the data to one mqtt server from both gateways

**Comment by DigiH** [comment]
I've just issued a new release 1.7.4 of Theengs Decoder with the Govee H5105 decoder included.

You can just update Theengs Decoder with

`pip install TheengsDecoder --upgrade`

after which your two H515s should be decoded and sent the temperature and humidity in their MQTT JSON messages now.

Grüße nach Mainz

**Comment by markusmainz** [comment]
cool i will check it immediately

**Comment by markusmainz** [comment]
Many THX it works well

**Comment by DigiH** [comment]
Thanks for the confirmation. 

Closing this.
