### ISSUE TITLE
Error running Theengs in WSL

### ISSUE THREAD

**Issue by simowilso** [theengs/gateway#254]
**Describe the bug**
Trying to run Theengs under WLS and get an error: 

INFO:BLEGateway:Starting BLE scan
INFO:BLEGateway:Connected to MQTT broker
INFO:BLEGateway:Subscribed to home/+/BTtoMQTT/undecoded
ERROR:BLEGateway:[org.freedesktop.DBus.Error.ServiceUnknown] The name org.bluez was not provided by any .service files

**To Reproduce**

- Install Theengs in WSL using pip
- start Theengs with: python3 -m TheengsGateway -H "192.168.0.54" -u "*****" -p "******" -padv 1

Error results:

INFO:BLEGateway:Starting BLE scan
INFO:BLEGateway:Connected to MQTT broker
INFO:BLEGateway:Subscribed to home/+/BTtoMQTT/undecoded
ERROR:BLEGateway:[org.freedesktop.DBus.Error.ServiceUnknown] The name org.bluez was not provided by any .service files

**Expected behavior**

no ERROR

**Screenshots**

**Environment**
Output of `python -m TheengsGateway.diagnose` or `python -m TheengsGateway.diagnose -c path_to_conf_file` if not using the default path for the configuration file.

**Additional context**
Add any other relevant context about the problem here.

**Comment by koenvervloesem** [comment]
It looks like WSL doesn't support Bluetooth.

**Comment by simowilso** [comment]
I think you are right :(
