### ISSUE TITLE
How to add a device...?

### ISSUE THREAD

**Issue by ciompek** [theengs/gateway#27]
I'm sorry if You find this question nooby but TBH I am a noob :)
I followed the instructions on https://theengs.github.io/gateway/ and I successfully installed the TheengsGateway on my Rpi.
I'm also successful in starting the service and connecting to a MQTT broker.
What I don't get is - how to connect my LYWSD03MMC ATC to that gateway? I have updated the firmware, in logs I can see the MAC of the device...

DEBUG:BLEGateway:A4:C1:38:7D:3B:A5 RSSI:-49 AdvertisementData(service_data={'0000fe95-0000-1000-8000-00805f9b34fb': b'0X[\x05\x01\xa5;}8\xc1\xa4(\x01\x00'})

Any1?

**Comment by koenvervloesem** [comment]
You don't connect to devices with Theengs Gateway. It just listens to advertisements broadcast by BLE devices and decodes these messages.

**Comment by ciompek** [comment]
@koenvervloesem  got it, thanks anyway
