### ISSUE TITLE
Allow choosing the bluetooth adapter to use

### ISSUE THREAD

**Issue by Lheriss** [theengs/gateway#37]
I'm discovering Theengs gateway as an Home Assistant Addon, and I plan to use another bluetooth adapter (dongle, acutally a Sena dongle) that has a better range. I don't find any way to specify the bluetooth interface that Theengs should use.

If possible, I'd like to be able to choose what bluetooth interface to use within the addon.

Thanks! Laurent

**Comment by koenvervloesem** [comment]
Yes, currently Theengs Gateway is automatically using your system's default Bluetooth adapter. I'll add the choice of adapter to the gateway. I've [added the same functionality](https://github.com/theengs/explorer/commit/e26442e1d6346381471e05a1ab15be0854d74b24) a few days ago to Theengs Explorer, and it's not much work.

By the way, which adapter is that exactly? I've been using the [April Brother USB Dongle 52840](https://wiki.aprbrother.com/en/BleUsbDongle.html#april-usb-dongle-52840) with Zephyr firmware as a Bluetooth adapter with better range, but I'm always looking for a longer range :-)

**Comment by koenvervloesem** [comment]
I've created a pull request with the requested functionality, and another pull request for the addon: https://github.com/mihsu81/addon-theengsgw/pull/5. So you should be able to use this soon.

**Comment by Lheriss** [comment]
Thank you, what a reactivity! I use a [Sena UD100](http://www.senanetworks.com/ud100-g03.html). Pricely, but really great! I

**Comment by mihsu81** [comment]
> Thank you, what a reactivity! I use a [Sena UD100](http://www.senanetworks.com/ud100-g03.html). Pricely, but really great! I

Out of curiosity, are you using it with HA OS?

**Comment by Lheriss** [comment]
Not yet : I use it with Jeedom. But I am moving to HA OS and will transfer it soon, now...

**Comment by mihsu81** [comment]
> Not yet : I use it with Jeedom. But I am moving to HA OS and will transfer it soon, now...

Cool. Please let me know how it goes if you get the chance. I'm looking for a powerful BT USB stick that would work in HA OS without having to rebuild it with additional drivers.
