### ISSUE TITLE
Setting up TheengsGateway/Mosquitto and Node-RED

### ISSUE THREAD

**Issue by tech9492** [theengs/gateway#65]
Hi all,

I wish to setup a real-time monitor and data logger for a Govee H5102 outside of the Govee app environment. The hardware I am using is a RPi 1B+ with Wi-Fi & BT/BLE provided by an ESP32(ESP-Hosted). 

I have already installed all the prerequisites; TheengsGateway, Mosquitto and Node-RED on the RPi 1B+. I went through the [TheengsGateway documenation](https://gateway.theengs.io/use/use.html#launching-the-gateway) several times but I am lost as to where to start to be able to stitch everything together. 

The RPi's IP is 10.0.0.X, Mosquitto is running on 10.0.0.X:1883. So, I tried the following command `python -m TheengsGateway -H 10.0.0.X -P 1883` but there is no output in terminal. Is this correct? I have not set any username and password so far for mosquitto, just want to make sure everything works as it should.

I would be very grateful if someone could guide me to piece that puzzle.

Thank you

**Comment by koenvervloesem** [comment]
Can you try again with option `-ll DEBUG`? And have you tried `-H localhost` if Mosquitto and Theengs Gateway are running on the same machine anyway?

**Comment by tech9492** [comment]
Hi @koenvervloesem 

Yes, Theengs Gateway, Mosquitto and Node-red are on the same machine.

Thank you for pointing out these options, `-ll DEBUG` is the output I was expecting from the TheengsGateway terminal. 

`-H localhost` solved the issue, mosquitto is receiving the decoded message.

 So, if TheengsGateway and Mosquitto are running on the same machine, it should be `-H localhost` instead of `-H <IP Address> -P <Port>`?

Thank you again.

**Comment by koenvervloesem** [comment]
Well, it totally depends on the configuration of Mosquitto and your Raspberry Pi OS (I suppose). Is Mosquitto listening on all interfaces? Is there a firewall running on your OS? Are you running these services as Docker containers? There are a lot of situations were you need to adapt. But for services running on the same machine directly (so not in a container), connecting to `localhost` is the most logical way. The default port is 1883, so it's not necessary to set it explicitly.

**Comment by tech9492** [comment]
1. > Is Mosquitto listening on all interfaces?

Yes, I presume it is listening on all interfaces since I have not touched the configuration file yet.

2. > Is there a firewall running on your OS? Are you running these services as Docker containers?

No, I am not running any firewall or Docker containers. As for the OS, it is the official Raspberry Pi OS (Bullseye 32bit).

3. > But for services running on the same machine directly (so not in a container), connecting to localhost is the most logical way. The default port is 1883, so it's not necessary to set it explicitly.

I thought it was interchangeable. But it is good to know running on the same machine, `localhost` is the way to go.

Thank you again.
