### ISSUE TITLE
Launching Theengs Gateway after boot up

### ISSUE THREAD

**Issue by tech9492** [theengs/gateway#73]
Hi all,

A brief description of my setup, I am running Theengs Gateway with Mosquitto as a broker and Node-red for dashboard and logging.

Mosquitto and Node-red run as services, hence starts at boot.

What are my options to autostart Theengs Gateway? Preferably after boot, just to keep troubleshooting simple for the future.

Thank you.

**Comment by koenvervloesem** [comment]
Here's how you do this with a systemd service:

https://github.com/theengs/gateway/discussions/5#discussioncomment-2282815

You can also do this with Theengs Gateway in a Docker container or as a snap.

**Comment by tech9492** [comment]
Hi @koenvervloesem 

Thank you very much for pointing that [link](https://github.com/theengs/gateway/discussions/5#discussioncomment-2282815).  That is exactly what I was looking for, and the process is documented with steps.

I have a question regarding the directory, you mention creating a systemd service in `/etc/systemd/system/TheengsGateway.service`. However, most of my services are found in `/usr/lib/systemd/system`. Can I create the TheengsGateway.service in the latter? Or it is advisable to create in `/etc/systemd/system`.

Thank you

**Comment by koenvervloesem** [comment]
`/etc/systemd/system` is advised for unit files created by yourself. `/usr/lib/systemd/system` is generally used by packages installed by your distribution's package manager.

**Comment by tech9492** [comment]
Hi @koenvervloesem 

Thank you for point out the differences between the two directories. 

Does the systemd service make use of `theengsgw.conf` ? 

Or should I input all my required arguments within this line `ExecStart=/usr/bin/python3 -m TheengsGateway -H host -u user -p password`? For example,`-sd 5 -tb 55`.

I had a go at it but the active status: failed. Please find below the output for `systemctl status TheengsGateway` .

` ● TheengsGateway.service - Theengs Gateway
     Loaded: loaded (/etc/systemd/system/TheengsGateway.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Wed 2022-11-02 19:55:03 +04; 10min ago
    Process: 682 ExecStart=/usr/bin/python3 -m TheengsGateway -H localhost -u xxxxxx -p xxxxxx -sd 5 -tb 55 (code=exited, status=1/FAILURE)
   Main PID: 682 (code=exited, status=1/FAILURE)
        CPU: 820ms

Nov 02 19:55:03 filamentpi systemd[1]: TheengsGateway.service: Scheduled restart job, restart counter is at 5.
Nov 02 19:55:03 filamentpi systemd[1]: Stopped Theengs Gateway.
Nov 02 19:55:03 filamentpi systemd[1]: TheengsGateway.service: Start request repeated too quickly.
Nov 02 19:55:03 filamentpi systemd[1]: TheengsGateway.service: Failed with result 'exit-code'.
Nov 02 19:55:03 filamentpi systemd[1]: Failed to start Theengs Gateway.`

Thank you

**Comment by koenvervloesem** [comment]
You should put all arguments in the `ExecStart` line.

Have a look at the other comments in the link I provided for the failure to start, for instance https://github.com/theengs/gateway/discussions/5#discussioncomment-2657243

If you can't find the cause of the error, try adding `-ll DEBUG` to the command line options and check the systemd logs with `journalctl -xe`.

**Comment by tech9492** [comment]
Hi @koenvervloesem 

I found my mistake, I thought I installed TheengsGateway using root privileges but I did not. After having installed it with `sudo`, the service is active and running.

> You should put all arguments in the ExecStart line.

I tried using scan duration (-sd) and time between scan (-tb), it does not seem to work. Is that normal when running TheengsGateway as a service?

Thank you.

**Comment by koenvervloesem** [comment]
> I tried using scan duration (-sd) and time between scan (-tb), it does not seem to work. Is that normal when running TheengsGateway as a service?

It should work. Can you confirm that this does work if you run the gateway manually on the same machine? And can you try this for a few combinations of scan duration and time between scan?

**Comment by bwduncan** [comment]
Just FWIW, I was successfully running from a systemd service, but I used `User=pi`.

**Comment by tech9492** [comment]
Yes I did run it manually w.r.t [TheengsGateway documentation](https://gateway.theengs.io/use/use.html), the interval between scans seems to be more predictable. However, with systemd service the incoming messages from `-ll DEBUG` is irregular.

I guess it is a hardware setup issue rather than software. I am actually using a RPi B+ with an ESP32 as a [network adapter](https://github.com/espressif/esp-hosted). So far, I managed to get both BLE and WiFi to work using SPI and I think that is the bottleneck of the setup. 

Have been trying to get BLE across UART and WiFi across SPI, but that route failed.
 
Thank you for all the help.

**Comment by seanmccabe** [comment]
> Just FWIW, I was successfully running from a systemd service, but I used `User=pi`.

Can you share your service, can't get mine to work constantly fails as above, but works directly in the command line

**Comment by bwduncan** [comment]
Of course! I make no guarantees for its accuracy or completeness, however. I just made it depend on some services that I thought it would need, and I installed the python package globally using `sudo pip install`, which I gather is somewhat discouraged....

```ini
[Unit]
Description=Theengs Gateway Bluetooth gateway
Requires=bluetooth.target network-online.target

[Service]
User=pi
ExecStart=/usr/bin/python3 -m TheengsGateway -s active

[Install]
WantedBy=multi-user.target
```
