### ISSUE TITLE
Document build instructions

### ISSUE THREAD

**Issue by koenvervloesem** [theengs/gateway#8]
**Is your feature request related to a problem? Please describe.**

I'd like to contribute some code to Theengs Gateway, but I'm not sure how to build the package.

**Describe the solution you'd like**

I'd like the build instructions to be documented like was done for Theengs Decoder in https://github.com/theengs/decoder/tree/development/python.

**Describe alternatives you've considered**

Trying to figure it out myself :-)

**Comment by 1technophile** [comment]
Cool, here are the instructions:
``` 
git clone https://github.com/theengs/gateway.git
cd gateway
git submodule update --init --recursive
python setup.py sdist
cd sdist
pip install distribution_file_name
```

After this you will need to launch the gateway outside of its folder. If not you are going to encounter errors.
