### ISSUE TITLE
Temperature negative

### ISSUE THREAD

**Issue by RudiAcacia** [theengs/gateway#92]
Depuis que j'ai fait la mise a jour à la version 0.7.0 et avec les températures que nous connaissons actuellement, je me suis rendu compte que cette version, ainsi que la 0.6.6 ne gère pas correctement les températures négatives.
exemple : pour une température de -1°C on obtient un résultat de 6552 °C sur un modele LYWSD03MMC

En faisant un retour arrière vers la version 0.6.0 les températures négatives sont correctement gérées

**Comment by DigiH** [comment]
This was fixed in Decoder and will be included with the next release of Gateway.

**Comment by DigiH** [comment]
Included in Gateway v0.8.0
